### PR TITLE
Added Command to start UDP application

### PR DESCRIPTION
**Pull request by rabinsahoo**
Added command for starting udp application at runtime

### CODE REVIEW

**Comment by nyrahul** [comment]
@rabinsahoo can you please fix the CI issue?
Seems the command handler is added currently to contiki only ... For RIOT you can simply add a placeholder and that should be fine.

**Comment by rabinsahoo** [comment]
OK Rahul

**Comment by nyrahul** [comment]
@rabinsahoo RIOT seems fine now ... But you havent sent PR for contiki ... Need to pull contiki changes first for this command to work.

**Comment by rabinsahoo** [comment]
For contiki I have sent it before.. do I need to send it again

**Pull request merged**
